[TAIPY]

[DATA_NODE.model_name]

[DATA_NODE.batch_size]

[DATA_NODE.run_name]

[DATA_NODE.results]

[DATA_NODE.output_path]

[TASK.train]
function = "algos.launch_train:function"
inputs = [ "model_name:SECTION", "batch_size:SECTION",]
outputs = [ "run_name:SECTION",]
skippable = "False:bool"

[TASK.get_results]
function = "algos.get_results:function"
inputs = [ "run_name:SECTION",]
outputs = [ "results:SECTION",]
skippable = "False:bool"

[TASK.infer]
function = "algos.run_inference:function"
inputs = [ "run_name:SECTION",]
outputs = [ "output_path:SECTION",]
skippable = "False:bool"

[SCENARIO.scenario_configuration]
tasks = [ "train:SECTION", "get_results:SECTION", "infer:SECTION",]
additional_data_nodes = []

[SCENARIO.scenario_configuration.comparators]

[SCENARIO.scenario_configuration.sequences]
